name: iOS Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  ios:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Selecciona Xcode disponible en el runner
      # Opci칩n A: fijar 15.4 (si est치 disponible en la imagen actual)
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.*'

      # Si prefieres usar el Xcode por defecto m치s reciente, elimina el bloque anterior
      # y usa esta otra opci칩n:
      # - name: Select latest Xcode 16
      #   uses: maxim-lobanov/setup-xcode@v1
      #   with:
      #     xcode-version: '16.*'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Flutter pub get
        run: flutter pub get

      - name: CocoaPods diagnose (optional)
        run: |
          if [ -f ios/Gemfile ]; then
            (cd ios && bundle exec pod repo update && bundle exec pod install --repo-update)
          else
            (cd ios && pod repo update && pod install --repo-update)
          fi
        continue-on-error: true
      - name: Force fresh Pods (Bundler)
        if: hashFiles('ios/Gemfile') != ''
        run: |
          rm -rf ios/Pods ios/Podfile.lock
          cd ios
          bundle exec pod repo update
          bundle exec pod install --repo-update

      - name: Build IPA (no codesign)
        run: |
          set -o pipefail
          flutter build ipa --no-codesign -v 2>&1 | tee build/ios/ipa_build_verbose.log

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-artifacts
          path: |
            build/ios/**/*
            ios/Pods/**/*
            **/DerivedData/**/*
          if-no-files-found: warn
